language: java
jdk: oraclejdk8
before_install:
- chmod +x gradlew
before_deploy:
- chmod ugo+x deploy.sh
script:
- bash ./gradlew clean build
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/garystafford/microservice-docker-demo-user.git
  - secure: dWZn1OWmt1OaO4rNZpqMiwMy82eDs1M+GtfH2GNBZF93//rC1Z1PvT/6UxSgJXbtj1t3gN9XlETXpkV0SQTflqtMdJg3xWXxVximjN+t3euXP6PT2jXzhr11HPRDHNe4JzEIWr/XX/bSnH1cJbOOOEa74Wv2SrWSam/awsSguSr10mFYugwyvGxYI4iaSFvDHnAKR41TaLnCzUunFFIb7a6v88gDtn650eVKGa6lg2EsF+Y5gI79JLNxESuf/CpJcVm9I/m1IniklQ6lyieRkhRJHbCQk9YGe6BIij25O9Ae3cFYn3+8Th1JNXMy1xZ1IEEAe3DpGO9ZDK0nYlRbNiCf5PzBiwKsva/aBEt2qRxh8ctW7amo6AY4mhk63d+WMtg6DkbMGXgnLpKoJjrztpzR6pun113c19PrvlZ9aJ6psW5yF2/qZUwOnvJktbZdQokEtjJ2avJYq5ztxyeUBOYo4eCzlQmYzivLXQu3PerIYG22bdgvkGtapoD6SwLI8bSXxrmJCO3HPUt9gGNp0QYvtrhWRDg/MPKMLajmdoPnX/3NZwXn53cvz5EisLaotRs6PcI7rue0Au9DtVHO2kZc+QKNgpVnK87ET5IMvrOrogk2yEFaZWxHrMN2OnVX/pLwkCoZUYkc11f8hkVdhbBhZ4ZkEIus9UXZlbmOTMc=
notifications:
  slack:
    secure: lQ9wlH21js1OMwStoDjMjPc/G1zdfE0UdbiR1kVunJ4FIowlLW6JHdU1186Jz8ouXoyzXhpT3NMj617QLm4alznBW0ndreieS9sybjhJS1gMNtLKJR9O2LXAwCWH+tQkXGDVOLygSvR/2Xlom+lFHr5Xg/IgWcGB3CO2pIIML3dOCojUstwKhoYSoxO8LpMFsZtXD+qpKeHTbVF7QSRXb3ghIYC15MNOs508z8Ed7vip5iNn/itUzSPsH1thBY2f80Fq4bh6WvQhvo2SsaUa01lw+btMbXA2FCQ3jAhZZG1SauuWXpEhgQ3IfOuWJRuDXY/kX+Q+dYjGqIH9qTT25svGEeMnUykfW3m1UrPe2G+9tJ9nyfWNxePlm4gWlzZhGha04UxVwBi+5DqiiS231ztDMQ/mWwp2Z6kUAgu97Om5lRov3zDXyI03vKCmiCTJx7NVLOiiWIqNqLth/ALfcdjtnHnwIH6bP+u26EmtHt5WjTP+PFbqIsFcLLtEQRlsFhUPhJY/2xO+jQrt0prYB0LC8hO9jDct9VIgju3D2y2BenecewV/GrHMVjhXxYbsW1gNAckZ34ZFUkfMRJegpCt81/vhhkrgJPmBespONROrcPI2ILSJTAXbUuwRIZ8Dcrnmg8/P/MbNsAIxrY4jH7RHV1JWM7/aoFaLsCUpj00=
